$c->{search}->{simple} = 
{
	search_fields => [
		{
			id => "q",
			meta_fields => [
				"title",
				"eprintid",
				"abstract",
				"ref_soporte",
				"documents",
		 		"subjects",
				"date", 
				"creators_name",
		 		"realizador_recolla_name",
				"informantes_name",
				"informante_grupo",
				"coleccion",
				#"dixitalizadores_name",
				"transcriptores_name",
				# "tipo_peza",
				"texto_peza", 
				"coleccion",
				"loc_concello",
				"loc_parroquia",
				"loc_lugar",
				#"divisions",
				"keywords",
				"ambito",
				"ambito_refran",
				"escala",
				"escala_refran",
				"numero_de_silabas",
				"numero_de_silabas_refran",
				"forma_musical",
				"forma_musical_refran",
				"incipit_melodico",
				"incipit_melodico_refran",
				"compas",
				"compas_refran",
				"incipit_do_texto",
				"incipit_do_texto_refran",
				"titulo_da_peza",
				"tempo",
				"instrumentos",
				"instrumentacion",
				"xenero",
				"modo_interpretacion",
				"cadencias",
				"cadencias_refran",
			]
		},
	],
	preamble_phrase => "cgi/search:preamble",
	title_phrase => "cgi/search:simple_search",
	citation => "result",
	page_size => 20,
	order_methods => {
		"byyear" 	 => "-date/creators_name/title",
		"byyearoldest"	 => "date/creators_name/title",
		"byname"  	 => "creators_name/-date/title",
		"bytitle" 	 => "title/creators_name/-date"
	},
	default_order => "byyear",
	show_zero_results => 1,
};
		
